### ISSUE TITLE
Weird newdoor issue

### ISSUE THREAD

**Issue by OfficialRDB** [BerkieBb/nui_doorlock#10]
I have a issue on a couple of doors for gangs.
I add the new door but the notification that it's locked is not on the door but on another spot.
![Capture](https://user-images.githubusercontent.com/50579206/139100569-d7face72-a848-47a0-80a8-aeb75e39e64b.PNG)
![Capture2](https://user-images.githubusercontent.com/50579206/139100573-239db59d-519d-4229-80dd-6a91adcbcc6d.PNG)

`table.insert(Config.DoorList, {
	objCoords = vector3(115.0398, -1961.364, 21.4227),
	lockpick = false,
	garage = false,
	maxDistance = 2.0,
	authorizedGangs = { ['ballas']=0 },
	doorID = 102,
	objHeading = 20.870018005372,
	locked = true,
	fixText = false,
	objHash = 23523831,
	audioRemote = false,
	slides = false,
})`

Maybe the door type issue. Because some of them work and and most are not single door.

**Comment by ZonixZA** [comment]
Getting the same issue, also with the balla doors

**Comment by OfficialRDB** [comment]
> 
> 
> Getting the same issue, also with the balla doors

I removed the MLO. The collision of the doors where way to big
