### ISSUE TITLE
When trying to use /newdoor im not getting the purple outline

### ISSUE THREAD

**Issue by highpixelmaster** [BerkieBb/nui_doorlock#12]
and also when i shoot the door im not getting it to actually create ive tried updating and reinstalling to no avail!

**Comment by BerkieBb** [comment]
Check your sever console after you tried creating a door

**Comment by highpixelmaster** [comment]
No errors

**Comment by BerkieBb** [comment]
Can you make a video showing you using /newdoor and after that show the console?

**Comment by Zulu1uk** [comment]
I got the same thing, it says aim and shoot at door and it does nothing.

**Comment by BerkieBb** [comment]
Try clearing your server cache

**Comment by Zulu1uk** [comment]
Same result

**Comment by Zulu1uk** [comment]
deleted all server cache, then started server https://cdn.discordapp.com/attachments/904424719682527268/909213015981821994/doorlock.png

shot a full round in both doors, i get no highlight or anything just full command like /newdoor [doortype] [locked] [jobs]

**Comment by Zulu1uk** [comment]
Got the highlighted area sorted, however im now getting SCRIPT ERROR: @nui_doorlock/server/main.lua:148: attempt to index a nil value local 'file')

**Comment by BerkieBb** [comment]
Are you on linux by any chance?

**Comment by Zulu1uk** [comment]
> Are you on linux by any chance?

Windows Server 2016

**Comment by BerkieBb** [comment]
When creating a new door, leave the optional fiels empty

**Comment by Zulu1uk** [comment]
> When creating a new door, leave the optional fiels empty

when i create a door i dont get the fancy popup where it shows gangs ect, just command only

**Comment by Zulu1uk** [comment]
scrap last reply, done as you said but same thing

**Comment by Zulu1uk** [comment]
https://discord.gg/FfP69sHW

I can show you via LIVE

**Comment by highpixelmaster** [comment]
This was still not resolved.

**Comment by BerkieBb** [comment]
There is only 1 solution I know of, make a new server with fresh files
