### ISSUE TITLE
No Permission

### ISSUE THREAD

**Issue by wousje01** [BerkieBb/nui_doorlock#16]
Hello,

console say 
![afbeelding](https://user-images.githubusercontent.com/56011454/141651033-3ba165a7-e96a-472f-a5ac-858951525fb8.png)

and i have god perms  what am I doing wrong ?

**Comment by BerkieBb** [comment]
Do you have god perms in the database permissions table?

**Comment by wousje01** [comment]
No, Sorry i'm so stupid, have only god acces from tx admin :P sorry my bad

thx for fast reaction
