### ISSUE TITLE
Field (Round) error

### ISSUE THREAD

**Issue by Aqade** [BerkieBb/nui_doorlock#21]
So I've been looking for a updated version of a doorlock and found this.
- The only issue here is, that whenever I unlock a door, I cant lock it again. It simple just staying unlocked despite the text says its locked.

The following error is what I get. 
- I've looked in the code, with not logic explination for why or what courses this.
- I've even tried reinstall the script, and tried out the PR's aswell as looked through all the issues

Hope this can be fixed.

Thank in advance!
![Skærmbillede 2021-12-04 121313](https://user-images.githubusercontent.com/64874485/144707410-d3f9c020-6658-447a-a5f1-0703d08fc97d.png)
.

**Comment by BerkieBb** [comment]
That error can be fixes by updating your qb-core

**Comment by Aqade** [comment]
> That error can be fixes by updating your qb-core

I'll try it, thanks.
