### ISSUE TITLE
Suggestion/Issue: Garage/sliding rates

### ISSUE THREAD

**Issue by JayseeXD** [BerkieBb/nui_doorlock#23]
Hello,

Originally started investigating this when I had issue with Gabz MRPD bollards outside (having to run into them).

It seems that the issue is that there is some animation time prior to them "unlocking" and after "locking them" (maybe some out of view sliding below ground?) I've found the best solution to this is to add the ability to set a rate to these which will speed up these animations.

I would suggest allowing users to set an additional parameter for rate or speed in the config files for garage doors and bollards using the following native. DoorSystemSetAutomaticRate(Config.DoorList[doorID].doorHash,3.0,false,false)

This will not only allow users to speed up slower animations on the bollards but garage doors can be sped up / slowed down to suit. 

Thanks in advance!
Jaysee

**Comment by regalonefour** [comment]
Hey, trying to fix the mrpd gates, mind sharing an example of how you used that native?

**Comment by BerkieBb** [comment]
Integrated with v2.1.0 as a config option
`doorRate = 3.0`
