### ISSUE TITLE
adding the default qb-bankrobbey locks so we can stop using qb-doorlocks

### ISSUE THREAD

**Issue by Skillgjii** [BerkieBb/nui_doorlock#25]
plis :D <3

**Comment by BerkieBb** [comment]
You can just add them yourself very easily

**Comment by WEEZOOKARP** [comment]
yes but the hacking minigames etc don't work with this
eg the gate at pacific standard wont open when you use security card

**Comment by BerkieBb** [comment]
Then you're doing it wrong
