### ISSUE TITLE
Issue : My doors not unlocking for my robberies

### ISSUE THREAD

**Issue by Themaddness** [BerkieBb/nui_doorlock#27]
My doors don't seem to unlock for my robberies , I added the right door id ect.

**Comment by BerkieBb** [comment]
If you updated, it works via name now so that's much easier to identify, because numbers as a doorid changed all the time if you used it with /newdoor in the past, now they can't unless you name 2 doors the same

**Comment by Themaddness** [comment]
what will the name of the door be for this just a bit confused,


-- Front Door
Config.DoorList[#Config.DoorList+1] = {
	audioRemote = false,
	maxDistance = 2.5,
	locked = true,
	authorizedJobs = { ['police']=0 },
	lockpick = false,
	slides = false,
	doors = {
		{objHash = 1425919976, objHeading = 306.00003051758, objCoords = vector3(-631.9554, -236.3333, 38.20653)},
		{objHash = 9467943, objHeading = 306.00003051758, objCoords = vector3(-630.4265, -238.4375, 38.20653)}
    },
	doorID = 106,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000
}

![thing](https://user-images.githubusercontent.com/96148420/146220704-cb19a867-7e71-489f-a40d-fdb89008b002.PNG)

**Comment by BerkieBb** [comment]
You have to name it, not search it up, you can give it a name of your choice when doing /newdoor
If you have updated that is

**Comment by Themaddness** [comment]
![image](https://user-images.githubusercontent.com/96148420/146223311-9493e899-e632-4fb8-8839-f534afd7989b.png)
So in this case do I put the name there

**Comment by BerkieBb** [comment]
Yes

**Comment by Themaddness** [comment]
Alright got it working thanks

**Comment by Aqade** [comment]
> 

Could you please share. What you did for the robbery to work with the doors. I just tried whatever you did, but without any luck. Maybe share the code from nui_doorlock and the code where the jewelery trigger the doors.
