### ISSUE TITLE
Cant add new doors via /newdoor

### ISSUE THREAD

**Issue by Aqade** [BerkieBb/nui_doorlock#29]
For starters, i've just got a new MLO for my server, which I decided needed some locks.
When I came across this problem:
- I got to the MLO and typed /newdoor, added the information i needed and then pressed "Submit".
- Other doing so, I had the purple outline of the door, trying to shoot at it. But it didn't add to the file.
- Then i tried to add it manually, with the coords of the doors. No luck either.

Then I tried to make a fresh install of a server and only added a few things such as hud and the main files for qb-core and standard scripts.
- Then I added this script from todays update.
- Tried again with same problem.

Here a short video of what I do and whats happening:
https://www.youtube.com/watch?v=e1fLLnkXcBQ

It does not make any sense, that it suddently doesn't work.
Is there a limit of how many "configs" that you can have ?

No errors in console or server console.

**Comment by P4R4NORM4L** [comment]
Same issue for me the config file does not save!

**Comment by helenclarko** [comment]
I'm also having an issue. 
I get the message: 

Successfully sent door data to the server

However, my door is not locked and I can walk right through it.

**Comment by TLRPDevelopment** [comment]
IF you changed the permissions to admin in config.lua you will need to change the server/main.lua line 101 from god to admin
**HasPermission(source, 'admin')**

**Comment by Aqade** [comment]
> 

Both the config, server.lua and my permission is all set to god. Still same problem.
- I even tried to just give me admin instead of god and change the script to have admin in config, server. Did not work either.

Just wish it was that easy. :)

**Comment by BerkieBb** [comment]
Any

**Comment by P4R4NORM4L** [comment]
Have you checked in the SQL Database if you're in the permissions table ?
