### ISSUE TITLE
davis pd cell door issues

### ISSUE THREAD

**Issue by regalonefour** [BerkieBb/nui_doorlock#30]
can upload a video for more info, but the cell doors in gabz new davis pd are very weird with this door lock, because nui sets the unlock at the very inside edge these doors basically overlap and don't properly unlock/lock. usually trying to unlock one door unlocks the other, trying to figure out how to offset the lock radius so that it properly overlays the doors

**Comment by AyPiXt** [comment]
use the mapdata doorlocks from gabz and its working then
