### ISSUE TITLE
DOOR LOCK UNLOCK ISSUE

### ISSUE THREAD

**Issue by Tafsir-Bhuiyan** [BerkieBb/nui_doorlock#32]
Locked door unlocked perfectly but when i try to lock the door its showing that its lockd but really it doesnt lock  :( 
help me to fix this error
![Screenshot (1018)](https://user-images.githubusercontent.com/95275471/147604698-8d56b3b6-56b4-46df-ae10-0a13e75bf455.png)

**Comment by BerkieBb** [comment]
You need to update you qb-core

**Comment by Tafsir-Bhuiyan** [comment]
bro i cant update my server right now :(
please give me old nui doorlock script
