### ISSUE TITLE
Door not worked

### ISSUE THREAD

**Issue by gamingt977** [BerkieBb/nui_doorlock#34]
I'll let the video explain, I can't really explain it.
https://streamable.com/9xyl5y

**Comment by BerkieBb** [comment]
Check the server console after making the door

**Comment by gamingt977** [comment]
Im not sure on how to give myself permissions 
![image](https://user-images.githubusercontent.com/77280523/147853910-4e034c1e-842d-4507-8725-4dc34474a2bd.png)

**Comment by BerkieBb** [comment]
You need to add god permissions in the permissions table in the database

**Comment by BerkieBb** [comment]
We have a tutorial for it in the QBCore discord
https://discord.gg/qbcore

**Comment by gamingt977** [comment]
In which bit of the discord

**Comment by gamingt977** [comment]
I have god tho

**Comment by BerkieBb** [comment]
In the database?

**Comment by gamingt977** [comment]
Fixed it now, I had to change the config in the nui_doorlocks
