### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jaylac2000** [BerkieBb/nui_doorlock#35]
im trying to convert and use this on a custom frame work

i am getting an error on \client\main @ line 404 

if RvMain.Shared.Round(Config.DoorList [doorID].currentHeading, 0) == RvMain.Shared.Round(Config.DoorList[doorID].objHeading, 0) then

![image](https://user-images.githubusercontent.com/53111006/147869184-d9edf3bc-c4bf-443a-af1f-f7e797dfdda3.png)

am i missing a function or something?

**Comment by BerkieBb** [comment]
Yes the qb-core/shared.lua has that function

**Comment by BerkieBb** [comment]
But that doesn't look like a custom framework

**Comment by jaylac2000** [comment]
i hella modified my version of qb-core

where is that function located?

**Comment by BerkieBb** [comment]
I just told you in the shared.lua, but don't call it a custom framework if you've only modified it, it's only a custom framework if it is made from scratch and doesn't look like other frameworks

**Comment by jaylac2000** [comment]
aha, ok ty

**Comment by jaylac2000** [comment]
```
RVRPShared.RandomStr = function(length)
	if length > 0 then
		return RVRPShared.RandomStr(length-1) .. StringCharset[math.random(1, #StringCharset)]
	else
		return ''
	end
end

RVRPShared.RandomInt = function(length)
	if length > 0 then
		return RVRPShared.RandomInt(length-1) .. NumberCharset[math.random(1, #NumberCharset)]
	else
		return ''
	end
end

RVRPShared.SplitStr = function(str, delimiter)
	local result = { }
	local from  = 1
	local delim_from, delim_to = string.find( str, delimiter, from  )
	while delim_from do
		table.insert( result, string.sub( str, from , delim_from-1 ) )
		from  = delim_to + 1
		delim_from, delim_to = string.find( str, delimiter, from  )
	end
	table.insert( result, string.sub( str, from  ) )
	return result
end
```
those are my only functions in the Shared.lua

Is is possible you can let me know what to add. I can't seem to find a Shared.lua file on the qb-framework/qb-core files

**Comment by jaylac2000** [comment]
nevermind found it. they did hella updates.. thanks
