### ISSUE TITLE
Doorlock Number

### ISSUE THREAD

**Issue by MrBeast2020** [BerkieBb/nui_doorlock#37]
In one of the older releases, u can find the door number in the config file, and so u can update it in the heist script adding the door number under the updatestate, but seems like it was taken off from this version is there a way to bring that back to the script? thank u!

**Comment by BerkieBb** [comment]
No, that was wrong with every restart, only worked after you added it or you had to be lucky to jot get it overwritten so I changed to door names which can't randomly change because of the table ordering
