### ISSUE TITLE
Doorlocks Dont Update when you join the city!!

### ISSUE THREAD

**Issue by GroveStreetStory** [BerkieBb/nui_doorlock#49]
I've had this issue for awhile and so have some other people ive spoken with.  If you spawn into a locked building the door locks dont sync / appear and you're stuck in the building!!

**Comment by BerkieBb** [comment]
I know, I will fix this with the rewrite of qb-doorlock and abandon this, qb-doorlock will be a better version of this

**Comment by BerkieBb** [comment]
I suggest you wait for qb-doorlock, it will be done by this week

**Comment by GroveStreetStory** [comment]
Awesome thanks for the quick response my man!
