### ISSUE TITLE
Unable to make locks on doors while using UncleJust's Diamond Casino Heists MLO.

### ISSUE THREAD

**Issue by dragon703** [BerkieBb/nui_doorlock#51]
While using the MLO for Diamond Casino Interior by UncleJust, the doors wont let me put locks on them. The /newdoor command brings up the form to fill up and upon choosing a target with aim the whole thing gets stuck. The door is permanently highlighted but the creation does not take place. I have checked for permission related issues as well and that does not seem to be the problem as well as I can create door locks all over the city.

The link for the MLO if needed is:
https://unclejust.tebex.io/package/4796051

Video for further clarification:
https://streamable.com/ynqbrz

**Comment by BerkieBb** [comment]
That's probably on UncleJust to fix then, because that probably means the doors are not recognised as they should by the game

**Comment by dragon703** [comment]
Oh, understood. If door props used are different from the ones that are already in the game, isn't there a way to introduce more door props in the list of recognized door props for the doorlock system?

**Comment by BerkieBb** [comment]
qb-doorlock v1 works very differently than this (v2 is wip by me)

**Comment by dragon703** [comment]
I understand. Thanks for the help.
